#!/bin/bash


clear
#g++ -ggdb `pkg-config --cflags opencv` -o `basename backgroundSubtractor.cpp .cpp` backgroundSubtractor.cpp `pkg-config --libs opencv` -lglut

g++ backgroundSubtractor.cpp TScan.cpp -std=c++11 -o BGS -lpthread `pkg-config --cflags --libs opencv`
