#!/bin/bash


clear


#for debugging
#g++ -g Main.cpp BScan.cpp SerialComm.cpp -std=c++11 -o execute -lpthread `pkg-config --cflags --libs opencv`

#release
g++ Main.cpp BScan.cpp SerialComm.cpp -std=c++11 -o execute -lpthread `pkg-config --cflags --libs opencv`
